apiVersion: v1
kind: DeploymentConfig
metadata:
  name: omar-jpip-app
  namespace: omar-dev
  selfLink: /oapi/v1/namespaces/omar-dev/deploymentconfigs/omar-jpip-app
  uid: ffdbbcd2-b4fc-11e7-ba3b-0e704fd9c8b2
  resourceVersion: '9375383'
  generation: 216
  creationTimestamp: '2017-10-19T18:40:37Z'
  labels:
    app: omar-jpip-app
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - omar-jpip-app
        from:
          kind: ImageStreamTag
          namespace: o2
          name: 'omar-jpip-app:latest'
        lastTriggeredImage: >-
          172.30.181.173:5000/o2/omar-jpip-app@sha256:ec50a1ba656f3ee72d6f2e0d681373803379c9fffc48c3a9aedab2e618bd188f
  replicas: 1
  test: false
  selector:
    app: omar-jpip-app
    deploymentconfig: omar-jpip-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: omar-jpip-app
        deploymentconfig: omar-jpip-app
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      volumes:
        - name: volume-xgf88
          persistentVolumeClaim:
            claimName: ossim-data-dev-pvc
      containers:
        - name: omar-jpip-app
          image: >-
            172.30.181.173:5000/o2/omar-jpip-app@sha256:ec50a1ba656f3ee72d6f2e0d681373803379c9fffc48c3a9aedab2e618bd188f
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_CLOUD_CONFIG_LABEL
              value: master
            - name: OSSIM_PREFS_FILE
              value: /usr/share/ossim/ossim-site-preferences
            - name: OSSIM_INSTALL_PREFIX
              value: /usr
            - name: OSSIM_DATA
              value: /data
          resources: {}
          volumeMounts:
            - name: volume-xgf88
              mountPath: /data
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
status:
  latestVersion: 213
  observedGeneration: 216
  replicas: 1
  updatedReplicas: 1
  availableReplicas: 1
  unavailableReplicas: 0
  details:
    message: image change
    causes:
      - type: ImageChange
        imageTrigger:
          from:
            kind: ImageStreamTag
            namespace: o2
            name: 'omar-jpip-app:latest'
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2017-11-27T20:50:36Z'
      lastTransitionTime: '2017-11-27T20:50:36Z'
      message: Deployment config has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2017-12-06T17:04:39Z'
      lastTransitionTime: '2017-12-06T17:04:37Z'
      reason: NewReplicationControllerAvailable
      message: replication controller "omar-jpip-app-213" successfully rolled out
  readyReplicas: 1
